version: "3.3"
services:
    web:
        build: ./
        command: nodemon -L server.js
        ports:
            - "80:80"
        depends_on:
            - mongo
        volumes:
            - ./uploads:/usr/src/app/uploads
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
            - .:/usr/src/app
            